on:
  schedule:
    - cron: '00 15 05 05 *' # 15:00 UTC = 8:30PM IST
  workflow_dispatch: 
jobs:
  make-repo-private:
    runs-on: ubuntu-latest
    steps:
      - run: gh repo edit ${{ github.repository }} --visibility private --accept-visibility-change-consequences 
        env:
          GH_TOKEN: ${{ secrets.MAKE_REPO_PUBLIC }}
